# config
cover: /img/img-bg.jpg
logo: /img/logo.svg
bio: 梦想一克拉 热血一卡车 眼泪一酒瓶 熬夜一光年

# Content
excerpt_link: 阅读更多

# Header  nav
menu:
  博客主页: /
  博客目录: /archives
  生活杂记: /mylife
  github: http://github.com/cky917
  关于我: /aboutMe/

##Private: /private

# nav.fonticon.css
navclass:
  博客主页: icon-home
  博客目录: icon-news
  生活杂记: icon-image
  github: icon-wiki
  关于我: icon-mail

##Private: icon-lock
rss: /atom.xml

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
